substitutions:
  name: "master-fan-light"
  friendly_name: "Master Bedroom"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: yes
  min_auth_mode: WPA2
  ap:
    ssid: "${friendly_name} Fallback"

api:
  encryption:
    key: !secret hass_encryption_key

ota:
  - platform: esphome
    password: !secret ota_key

packages:
  device:
    url: https://github.com/cyberglitchlabs/esphome
    files: [packages/ifan04_base.yaml]
    ref: main
    refresh: 1d
