# Example configuration for ANAVI Fume Extractor
# Copy this file to your ESPHome config directory and customize

substitutions:
  name: "fume-extractor"
  friendly_name: "Fume Extractor"

packages:
  device:
    url: https://github.com/cyberglitchlabs/esphome
    files: [packages/anavi_fume_extractor.yaml]
    ref: main
    refresh: 1d

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${friendly_name} Fallback"

api:

ota:
  - platform: esphome
  - platform: web_server

web_server:
  port: 80
