substitutions:
  name: "workshop-fume-extractor"
  friendly_name: "Workshop Fume Extractor"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

packages:
  remote_package:
    url: github://cyberglitchlabs/esphome/packages/anavi_fume_extractor.yaml
    ref: main
