# Example configuration for OWON XDM1041 Multimeter Remote
# Copy this file to your ESPHome config directory and customize

substitutions:
  name: "lab-multimeter"
  friendly_name: "Lab Multimeter"

packages:
  device:
    url: https://github.com/cyberglitchlabs/esphome
    files: [packages/owon_xdm_base.yaml]
    ref: main
    refresh: 1d

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${friendly_name} Fallback"

api:

ota:
  - platform: esphome
  - platform: web_server

web_server:
  port: 80

# Optional: MQTT Support
# Uncomment the package below and comment out the one above to enable MQTT
# Then configure the mqtt: section below

# packages:
#   device:
#     url: https://github.com/cyberglitchlabs/esphome
#     files: [packages/owon_xdm_with_mqtt.yaml]
#     ref: main
#     refresh: 1d

# mqtt:
#   broker: !secret mqtt_broker
#   port: !secret mqtt_port
#   username: !secret mqtt_user
#   password: !secret mqtt_password
#   discovery: true
#   discovery_prefix: homeassistant
