substitutions:
  # Unique ID for this device
  name: "living-room-plug"
  friendly_name: "Living Room Plug"
  
  # WiFi Credentials
  # You can use string literals here or !secret if you have a local secrets.yaml
  wifi_ssid: "MyWiFiSSID" 
  wifi_password: "MyWiFiPassword"
  # wifi_ssid: !secret wifi_ssid
  # wifi_password: !secret wifi_password

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

packages:
  remote_package:
    # URL to the packages/s31_base.yaml in your remote repo
    # If you have forked this repo, replace 'cyberglitchlabs/esphome' with your fork's path
    url: github://cyberglitchlabs/esphome/packages/s31_base.yaml
    ref: main
    # When using remote_package, esphome will fetch the file and any relative !includes 
    # (like core.yaml and sonoff_s31.yaml)
