substitutions:
  name: "living-room-plug"
  friendly_name: "Living Room Plug"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

dashboard_import:
  package_import_url: github://cyberglitchlabs/esphome/packages/s31_base.yaml
  import_full_config: false

# WiFi Configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback"
    password: ""

# Enable Home Assistant API
api:

# Enable Over-The-Air updates
ota:
  - platform: esphome
  - platform: web_server

# Optional: Web server for direct device access
web_server:
  port: 80

# Time sync
time:
  - platform: homeassistant
    id: esptime

# Include Sonoff S31 hardware package
packages:
  remote_package:
    url: https://github.com/cyberglitchlabs/esphome
    files: [packages/s31_base.yaml]
    ref: main
    refresh: 1d
