# Example: Shared automation configuration
# Add your common automations here
# Example:
# automation:
#   - alias: 'Restart on WiFi disconnect'
#     trigger:
#       - platform: wifi
#         event: disconnected
#     action:
#       - service: esphome.restart
