esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true
  project:
    name: cyberglitchlabs.anavi-fume-extractor
    version: ${config_version}

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Unique pin configuration for ANAVI Fume Extractor ESP32-S3
substitutions:
  fan_pwm_pin: GPIO27
  buzzer_pin: GPIO26
  button_pin: GPIO25
  rotary_a_pin: GPIO32
  rotary_b_pin: GPIO33
  mq135_pin: GPIO36
  dht22_pin: GPIO4
  bmp180_addr: 0x77
  bh1750_addr: 0x23
  i2c_sda: GPIO21
  i2c_scl: GPIO22
  mq135_temp_sensor: dht22_temperature
  mq135_hum_sensor: dht22_humidity
