# Shared rotary encoder config
sensor:
  - platform: rotary_encoder
    name: "Fan Speed Encoder"
    pin_a: ${rotary_a_pin}
    pin_b: ${rotary_b_pin}
    min_value: 0
    max_value: 100
    resolution: 1
    id: fan_speed_encoder
