substitutions:
  friendly_name: "ANAVI Fume Extractor"

esp8266:
  board: esp12e
  restore_from_flash: true

esphome:
  project:
    name: "anavi.fume_extractor"
    version: "1.0.0"

logger:
  level: DEBUG

# I2C Bus for all sensors and OLED display
i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true
  id: bus_a

# Fan control via relay
switch:
  - platform: gpio
    pin: GPIO12
    name: "${friendly_name} Fan"
    id: fan_relay
    icon: "mdi:fan"
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - display.page.show: page_fan_on
    on_turn_off:
      - display.page.show: page_status

# Physical button to control fan (GPIO13)
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Button"
    id: fan_button
    on_press:
      - switch.toggle: fan_relay
  
  - platform: status
    name: "${friendly_name} Status"

# LED indicator (GPIO16)
output:
  - platform: gpio
    pin: GPIO16
    id: status_led_output
    inverted: false

light:
  - platform: binary
    name: "${friendly_name} Status LED"
    output: status_led_output
    id: status_led
    restore_mode: ALWAYS_OFF

# MQ-135 Air Quality Sensor (Analog A0)
sensor:
  - platform: adc
    pin: A0
    name: "${friendly_name} Air Quality"
    id: air_quality_sensor
    update_interval: 60s
    filters:
      - lambda: |-
          // Convert to conductivity percentage
          float conductivity = (x / 3.3) * 100.0;
          return conductivity;
    unit_of_measurement: "%"
    accuracy_decimals: 0
    icon: "mdi:air-filter"

  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

  # HTU21D Temperature and Humidity Sensor
  - platform: htu21d
    temperature:
      name: "${friendly_name} Temperature"
      id: htu_temperature
    humidity:
      name: "${friendly_name} Humidity"
      id: htu_humidity
    update_interval: 60s

  # BH1750 Light Sensor
  - platform: bh1750
    name: "${friendly_name} Illuminance"
    id: light_sensor
    address: 0x23
    update_interval: 60s

  # BMP180 Temperature and Pressure Sensor
  - platform: bmp085
    temperature:
      name: "${friendly_name} BMP Temperature"
      id: bmp_temperature
    pressure:
      name: "${friendly_name} Pressure"
      id: bmp_pressure
    update_interval: 60s

  # APDS9960 for color and gesture detection
  - platform: apds9960
    type: CLEAR
    name: "${friendly_name} Clear Light"
    id: apds_clear
  - platform: apds9960
    type: RED
    name: "${friendly_name} Red Light"
  - platform: apds9960
    type: GREEN
    name: "${friendly_name} Green Light"
  - platform: apds9960
    type: BLUE
    name: "${friendly_name} Blue Light"
  - platform: apds9960
    type: PROXIMITY
    name: "${friendly_name} Proximity"

# APDS9960 Gesture Support
apds9960:
  address: 0x39
  update_interval: 60s

# Text sensor for air quality status
text_sensor:
  - platform: template
    name: "${friendly_name} Air Quality Status"
    id: air_quality_status
    icon: "mdi:gauge"
    lambda: |-
      float conductivity = id(air_quality_sensor).state;
      if (conductivity <= 18) {
        return {"Good"};
      } else if (conductivity <= 36) {
        return {"Moderate"};
      } else if (conductivity <= 54) {
        return {"Unhealthy"};
      } else if (conductivity <= 72) {
        return {"Very Unhealthy"};
      } else {
        return {"Hazardous"};
      }
    update_interval: 60s

  - platform: template
    name: "${friendly_name} Dangerous Gas"
    id: dangerous_gas
    icon: "mdi:biohazard"
    lambda: |-
      float conductivity = id(air_quality_sensor).state;
      return (conductivity > 36) ? std::string("on") : std::string("off");
    update_interval: 60s

# Mini OLED Display (128x64, I2C)
font:
  - file: "gfonts://Roboto"
    id: font_small
    size: 12
  - file: "gfonts://Roboto"
    id: font_medium
    size: 14
  - file: "gfonts://Roboto"
    id: font_large
    size: 16

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    id: oled_display
    update_interval: 5s
    pages:
      - id: page_status
        lambda: |-
          // Status page showing temperature and humidity
          it.printf(0, 0, id(font_large), "Fume Extractor");
          if (id(htu_temperature).has_state()) {
            it.printf(0, 20, id(font_medium), "Temp: %.1f°C", id(htu_temperature).state);
          }
          if (id(htu_humidity).has_state()) {
            it.printf(0, 36, id(font_medium), "Hum: %.0f%%", id(htu_humidity).state);
          }
          if (id(air_quality_status).has_state()) {
            it.printf(0, 52, id(font_small), "Air: %s", id(air_quality_status).state.c_str());
          }
      
      - id: page_fan_on
        lambda: |-
          // Fan active page
          it.printf(0, 0, id(font_large), "Fume Extractor");
          it.printf(0, 24, id(font_large), "FAN: ON");
          if (id(air_quality_status).has_state()) {
            it.printf(0, 48, id(font_medium), "Air: %s", id(air_quality_status).state.c_str());
          }
