# ⚠️ DEPRECATED - This file is no longer used ⚠️
# 
# This repository has been refactored to follow the AirGradient modular pattern.
# Users should now define wifi, api, ota, and other core components directly 
# in their device configuration files.
#
# See examples/ directory for updated usage patterns.
#
# This file is kept for backward compatibility but may be removed in the future.

substitutions:
  wifi_ssid: 
  wifi_password: 
  # Default to WPA2-PSK for security, but allow override
  wifi_min_auth_mode: "WPA2"

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  fast_connect: true
  
  # Security setting to avoid warning
  min_auth_mode: ${wifi_min_auth_mode}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "FallBack Hotspot"
    password: ""

api:

ota:
  - platform: esphome
  - platform: web_server

# Required for ota: platform: web_server
web_server:
  port: 80

time:
  - platform: sntp
    id: my_time
