substitutions:
  friendly_name: "Current Affairs"
  # The factor for the CT clamp (10A/1V)
  ct_factor: "10"
  # The update interval for the sensors
  update_interval: 60s
  # The sample duration for the CT clamp
  sample_duration: 1s
  # Nominal RMS voltage for power calculation
  rms_voltage: "120"

dashboard_import:
  package_import_url: github://cyberglitchlabs/esphome/packages/current_affairs.yaml
  import_full_config: false

esphome:
  project:
    name: "cyberglitchlabs.current_affairs"
    version: "1.0.0"

esp8266:
  board: d1_mini

time:
  - platform: homeassistant
    id: esptime

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true

ads1115:
  - address: 0x48
    continuous_mode: true
    id: ads48_hub
  - address: 0x49
    continuous_mode: true
    id: ads49_hub
  - address: 0x4A
    continuous_mode: true
    id: ads4A_hub
  - address: 0x4B
    continuous_mode: true
    id: ads4B_hub

sensor:
  # ADS1115 at 0x48
  - platform: ads1115
    ads1115_id: ads48_hub
    multiplexer: 'A0_A1'
    gain: 1.024
    sample_rate: 860
    id: ads48_0_1_raw
    update_interval: never
  - platform: ads1115
    ads1115_id: ads48_hub
    multiplexer: 'A2_A3'
    gain: 1.024
    sample_rate: 860
    id: ads48_2_3_raw
    update_interval: never

  # ADS1115 at 0x49
  - platform: ads1115
    ads1115_id: ads49_hub
    multiplexer: 'A0_A1'
    gain: 1.024
    sample_rate: 860
    id: ads49_0_1_raw
    update_interval: never
  - platform: ads1115
    ads1115_id: ads49_hub
    multiplexer: 'A2_A3'
    gain: 1.024
    sample_rate: 860
    id: ads49_2_3_raw
    update_interval: never

  # ADS1115 at 0x4A
  - platform: ads1115
    ads1115_id: ads4A_hub
    multiplexer: 'A0_A1'
    gain: 1.024
    sample_rate: 860
    id: ads4A_0_1_raw
    update_interval: never
  - platform: ads1115
    ads1115_id: ads4A_hub
    multiplexer: 'A2_A3'
    gain: 1.024
    sample_rate: 860
    id: ads4A_2_3_raw
    update_interval: never

  # ADS1115 at 0x4B
  - platform: ads1115
    ads1115_id: ads4B_hub
    multiplexer: 'A0_A1'
    gain: 1.024
    sample_rate: 860
    id: ads4B_0_1_raw
    update_interval: never
  - platform: ads1115
    ads1115_id: ads4B_hub
    multiplexer: 'A2_A3'
    gain: 1.024
    sample_rate: 860
    id: ads4B_2_3_raw
    update_interval: never

  # CT Clamp Sensors
  - platform: ct_clamp
    sensor: ads48_0_1_raw
    name: "Channel J1 Current"
    id: j1_current
    update_interval: ${update_interval}
    sample_duration: ${sample_duration}
    unit_of_measurement: "A"
    device_class: current
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
    entity_category: diagnostic

button:
  - platform: restart
    name: "${friendly_name} Restart"
    entity_category: config

  - platform: safe_mode
    name: "${friendly_name} Safe Mode"
    entity_category: config

  - platform: total_daily_energy
    name: "Channel J2 Energy"
    sensor: j2_power
    id: j2_energy
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.001
  - platform: total_daily_energy
    name: "Channel J3 Energy"
    sensor: j3_power
    id: j3_energy
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.001
  - platform: total_daily_energy
    name: "Channel J4 Energy"
    sensor: j4_power
    id: j4_energy
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.001
  - platform: total_daily_energy
    name: "Channel J5 Energy"
    sensor: j5_power
    id: j5_energy
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.001
  - platform: total_daily_energy
    name: "Channel J6 Energy"
    sensor: j6_power
    id: j6_energy
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.001
  - platform: total_daily_energy
    name: "Channel J7 Energy"
    sensor: j7_power
    id: j7_energy
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.001
  - platform: total_daily_energy
    name: "Channel J8 Energy"
    sensor: j8_power
    id: j8_energy
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.001
