# Sonoff iFan04 hardware definition
# Complete package for controlling Sonoff iFan04 ceiling fan controller
# Users should define their own esphome, wifi, api, ota in their device config
#
# Features:
# - 3-speed fan control via capacitor switching
# - Light relay control
# - RF remote support (433MHz)
# - Buzzer feedback with morse code patterns
# - Optional fan startup boost
# - Physical button support

substitutions:
  friendly_name: "iFan04"
  # Fan startup boost time (optional override)
  fan_startup_boost_time: 5s
  
  # Morse codes for the different buzzer sounds
  code_buzzer_on:  "E"    # .
  code_buzzer_off: "I"    # ..
  code_fan_off:    "T"    # -
  code_fan_1:      "N"    # -.
  code_fan_2:      "D"    # -..
  code_fan_3:      "B"    # -...
  code_rc_unpair:  "O"    # ---
  code_short:      "E"    # .
  code_long:       "T"    # -

dashboard_import:
  package_import_url: github://cyberglitchlabs/esphome/packages/ifan04_base.yaml
  import_full_config: false

esphome:
  project:
    name: "cyberglitchlabs.sonoff_ifan04"
    version: "1.0.0"
  on_boot:
    - priority: 600
      then:
        - output.turn_off: buzzer
        - globals.set: # needed to disable actions on switch initialization (state restore)
            id: switches_initialized
            value: "true"

external_components:
  - source:
      type: git
      url: https://github.com/rh1rich/esphome-ifan-remote
  - source:
      type: git
      url: https://github.com/rh1rich/esphome-morse-code

esp8266:
  board: esp8285
  early_pin_init: false
  restore_from_flash: true

preferences:
  flash_write_interval: 5min

# Logger setup to avoid interference with RF receiver on UART0
logger:
  baud_rate: 0
  level: INFO

# RF Remote Receiver
uart:
  rx_pin: GPIO03
  baud_rate: 9600
  id: uart_bus

status_led:
  pin:
    number: GPIO13
    inverted: true

output:
  - platform: gpio
    id: light_relay
    pin:
      number: GPIO09
      inverted: true
  - platform: gpio
    id: buzzer
    pin:
      number: GPIO10
      inverted: true
  - platform: gpio
    id: fan_relay_1
    pin: GPIO14
  - platform: gpio
    id: fan_relay_2
    pin: GPIO12
  - platform: gpio
    id: fan_relay_3
    pin: GPIO15
  - platform: template
    id: fan_relays
    type: float
    write_action:
      - if:
          condition:
            lambda: return (state < 0.3);
          then:
            - if:
                condition:
                  lambda: return id(buzzer_enabled).state;
                then:
                  - morse_code.start: $code_fan_off
            - script.execute:
                id: fan_speed_set
                speed: 0
      - if:
          condition:
            lambda: return ((state >= 0.3) && (state < 0.6));
          then:
            - if:
                condition:
                  lambda: return id(buzzer_enabled).state;
                then:
                  - morse_code.start: $code_fan_1
            - script.execute:
                id: fan_speed_set
                speed: 1
      - if:
          condition:
            lambda: return ((state >= 0.6) && (state < 0.9));
          then:
            - if:
                condition:
                  lambda: return id(buzzer_enabled).state;
                then:
                  - morse_code.start: $code_fan_2
            - script.execute:
                id: fan_speed_set
                speed: 2
      - if:
          condition:
            lambda: return (state >= 0.9);
          then:
            - if:
                condition:
                  lambda: return id(buzzer_enabled).state;
                then:
                  - morse_code.start: $code_fan_3
            - script.execute:
                id: fan_speed_set
                speed: 3

morse_code:
  output: buzzer
  dit_duration: 50

light:
  - platform: binary
    name: '${friendly_name} Light'
    id: light_comp
    output: light_relay

fan:
  - platform: speed
    name: '${friendly_name} Fan'
    id: fan_comp
    output: fan_relays
    speed_count: 3

switch:
  - platform: template
    name: '${friendly_name} Buzzer enabled'
    id: buzzer_enabled
    entity_category: config
    optimistic: True
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      - if: # only trigger action after the switch is initially set (restored)
          condition:
            lambda: return (id(switches_initialized));
          then:
            - morse_code.start: $code_buzzer_on
    on_turn_off:
      - if: # only trigger action after the switch is initially set (restored)
          condition:
            lambda: return (id(switches_initialized));
          then:
            - morse_code.start: $code_buzzer_off
  - platform: template
    name: '${friendly_name} Light enabled'
    id: light_enabled
    entity_category: config
    optimistic: True
    restore_mode: RESTORE_DEFAULT_ON
  - platform: template
    name: '${friendly_name} Fan startup-boost enabled'
    id: fan_boost_enabled
    entity_category: config
    optimistic: True
    restore_mode: RESTORE_DEFAULT_OFF

button:
  - platform: restart
    name: '${friendly_name} Restart'
    entity_category: diagnostic

  - platform: safe_mode
    name: '${friendly_name} Safe Mode'
    entity_category: config

sensor:
  - platform: uptime
    name: '${friendly_name} Uptime'
    entity_category: diagnostic
    unit_of_measurement: s
  - platform: wifi_signal
    id: wifi_signal_db
    name: '${friendly_name} WiFi Signal dB'
    entity_category: diagnostic
  - platform: copy
    id: wifi_signal_rel
    source_id: wifi_signal_db
    name: "${friendly_name} WiFi Signal"
    entity_category: diagnostic
    filters:
      - lambda: |-
          return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    device_class: 'signal_strength'

binary_sensor:
  - platform: gpio
    name: "${friendly_name} Button"
    pin:
      number: GPIO00
      inverted: true
  - platform: status
    name: "${friendly_name} Status"
    entity_category: diagnostic
  - platform: template
    name: "${friendly_name} RC button light"
    id: rc_button_light
    filters:
      - delayed_off: 300ms
  - platform: template
    name: "${friendly_name} RC button RF/WiFi"
    id: rc_button_rfwifi
    filters:
      - delayed_off: 300ms
  - platform: template
    name: "${friendly_name} RC button WiFi (long)"
    id: rc_button_wifi_long
    filters:
      - delayed_off: 300ms
  - platform: template
    name: "${friendly_name} RC button RF (long)"
    id: rc_button_rf_long
    filters:
      - delayed_off: 300ms

ifan_remote:
  on_command:
    then:
      - if:
          condition:
            lambda: return (command.high == 0x0104 && command.low == 0x000100);
          then:
            - fan.turn_off: fan_comp
      - if:
          condition:
            lambda: return (command.high == 0x0104 && command.low == 0x000101);
          then:
            - fan.turn_on:
                id: fan_comp
                speed: 1
      - if:
          condition:
            lambda: return (command.high == 0x0104 && command.low == 0x000102);
          then:
            - fan.turn_on:
                id: fan_comp
                speed: 2
      - if:
          condition:
            lambda: return (command.high == 0x0104 && command.low == 0x000103);
          then:
            - fan.turn_on:
                id: fan_comp
                speed: 3
      - if:
          condition:
            lambda: return (command.high == 0x0104 && command.low == 0x000104);
          then:
            - if:
                condition:
                  lambda: return id(light_enabled).state;
                then:
                  - light.toggle: light_comp
                else:
                  - if:
                      condition:
                        lambda: return id(buzzer_enabled).state;
                      then:
                        - morse_code.start: $code_short
                  - binary_sensor.template.publish:
                      id: rc_button_light
                      state: ON
                  - binary_sensor.template.publish:
                      id: rc_button_light
                      state: OFF
      - if:
          condition:
            lambda: return (command.high == 0x0106 && command.low == 0x000101);
          then:
            - switch.toggle: buzzer_enabled
      - if:
          condition:
            lambda: return (command.high == 0x0101 && command.low == 0x000102);
          then:
            - if:
                condition:
                  lambda: return id(buzzer_enabled).state;
                then:
                  - morse_code.start: $code_short
            - binary_sensor.template.publish:
                id: rc_button_rfwifi
                state: ON
            - binary_sensor.template.publish:
                id: rc_button_rfwifi
                state: OFF
      - if:
          condition:
            lambda: return (command.high == 0x0101 && command.low == 0x000101);
          then:
            - if:
                condition:
                  lambda: return id(buzzer_enabled).state;
                then:
                  - morse_code.start: $code_long
            - binary_sensor.template.publish:
                id: rc_button_wifi_long
                state: ON
            - binary_sensor.template.publish:
                id: rc_button_wifi_long
                state: OFF
      - if:
          condition:
            lambda: return (command.high == 0x0107 && command.low == 0x000101);
          then:
            - morse_code.start: $code_rc_unpair
            - binary_sensor.template.publish:
                id: rc_button_rf_long
                state: ON
            - binary_sensor.template.publish:
                id: rc_button_rf_long
                state: OFF

text_sensor:
  - platform: version
    name: '${friendly_name} ESPHome Version'
    entity_category: diagnostic
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} WiFi IP Address
      entity_category: diagnostic
    ssid:
      name: ${friendly_name} WiFi SSID
      entity_category: diagnostic
    mac_address:
      name: ${friendly_name} WiFi MAC Address
      entity_category: diagnostic
    dns_address:
      name: ${friendly_name} WiFi DNS Address
      entity_category: diagnostic

globals:
  - id: last_fan_speed
    type: int
    restore_value: no
    initial_value: "0"
  - id: switches_initialized
    type: bool
    restore_value: no
    initial_value: "false"

script:
  - id: fan_speed_set
    mode: restart
    parameters:
      speed: int
    then:
      - if:
          condition:
            lambda: return (speed == 0);
          then:
            - output.turn_off: fan_relay_1
            - output.turn_off: fan_relay_2
            - output.turn_off: fan_relay_3
          else:
            - if:
                condition:
                  lambda: return (id(fan_boost_enabled).state && (id(last_fan_speed) == 0));
                then:
                  - output.turn_off: fan_relay_1
                  - output.turn_off: fan_relay_2
                  - output.turn_on: fan_relay_3
                  - delay: $fan_startup_boost_time
            - if:    # enable cap 1
                condition:
                  lambda: return (speed == 1);
                then:
                  - output.turn_on: fan_relay_1
                  - output.turn_off: fan_relay_2
                  - output.turn_off: fan_relay_3
            - if:    # enable cap 1 & 2
                condition:
                  lambda: return (speed == 2);
                then:
                  - output.turn_on: fan_relay_1
                  - output.turn_on: fan_relay_2
                  - output.turn_off: fan_relay_3
            - if:    # no caps
                condition:
                  lambda: return (speed == 3);
                then:
                  - output.turn_off: fan_relay_1
                  - output.turn_off: fan_relay_2
                  - output.turn_on: fan_relay_3
      - lambda: |-
          id(last_fan_speed) = speed;
