esphome:
  project:
    name: "cyberglitchlabs.ikea_vindriktning"
    version: "1.0.0"

esp8266:
  board: esp01_1m

# The PM1006 sensor uses UART to communicate.
# Typical wiring for VINDRIKTNING is:
# IKEA (Rest) -> ESP8266 RX (GPIO3/RX)
uart:
  rx_pin: GPIO3
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "Particulate Matter 2.5µm Concentration"
