# Sonoff S31 hardware definition
# Users should define their own esphome, wifi, api, ota in their device config

packages:
  device:
    url: https://github.com/cyberglitchlabs/esphome
    files: [packages/sonoff_s31.yaml]
    ref: main

dashboard_import:
  package_import_url: github://cyberglitchlabs/esphome/packages/s31_base.yaml
  import_full_config: false

esphome:
  project:
    name: "cyberglitchlabs.sonoff_s31"
    version: "1.0.0"
