substitutions:
  friendly_name: "Sonoff S31"

esp8266:
  board: esp12e
  early_pin_init: false
  restore_from_flash: false

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)
  logs:
    sensor: DEBUG # (Overide any global setting, to VERBOSE will spamming the cse7766 sensors)

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "${friendly_name} Status"

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    current:
      name: "${friendly_name} Current"
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s
    voltage:
      name: "${friendly_name} Voltage"
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s
    power:
      name: "${friendly_name} Power"
      accuracy_decimals: 2
      id: my_power
      filters:
        - throttle_average: 60s
    energy:
      name: "${friendly_name} Energy"
      accuracy_decimals: 2
      filters:
        - throttle: 60s
    apparent_power: #(only available with version 2024.3.0 or greater)
      name: "${friendly_name} Apparent Power"
      filters:
        - throttle_average: 60s
    power_factor: #(only available with version 2024.3.0 or greater)
      name: "${friendly_name} Power Factor"
      accuracy_decimals: 2
      filters:
        - throttle_average: 60s

  - platform: total_daily_energy #(Optional, not specific to cse7766)
    name: "${friendly_name} Daily Energy"
    power_id: my_power
    accuracy_decimals: 2

switch:
  - platform: gpio
    name: "${friendly_name} Relay"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_OFF

status_led:
  pin:
    number: GPIO13
    inverted: True
